# Branches that trigger a build on commit
trigger:
- master

# Branches that trigger builds on PR
pr:
- master

jobs:

- job: Windows
  pool:
    name: NetCorePublic-Int-Pool
    queue: buildpool.windows.10.amd64.vs2017.open
  variables:
    _os: Windows
  strategy:
    maxParallel: 2
    matrix:
      Debug:
        _configuration: Debug
      Release:
        _configuration: Release
  timeoutInMinutes: 20
  steps:
    - script: $(Build.SourcesDirectory)\eng\common\cibuild.cmd -configuration $(_configuration) -prepareMachine
      displayName: Build and Test
    - task: PublishTestResults@1
      inputs:
        testRunner: XUnit
        testResultsFiles: '$(Build.SourcesDirectory)\artifacts\TestResults\$(_configuration)\*.xml'
        mergeTestResults: true
        testRunTitle: '$(_os) $(_configuration)'
      condition: always()
    - task: PublishBuildArtifacts@1
      displayName: Publish Logs
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)\artifacts\log\$(_configuration)'
        ArtifactName: '$(_os) $(_configuration)'
      continueOnError: true
      condition: not(succeeded())

- job: Linux
  pool: 
   name: NetCorePublic-Int-Pool
   queue: buildpool.ubuntu.1604.amd64.open
  variables:
    _os: Linux
  strategy:
    maxParallel: 2
    matrix:
      Debug:
        _configuration: Debug
      Release:
        _configuration: Release
  timeoutInMinutes: 90
  steps:
    - script: $(Build.SourcesDirectory)/eng/common/cibuild.sh --configuration $(_configuration) --prepareMachine
      displayName: Build and Test
    - task: PublishTestResults@2
      displayName: Publish xUnit Test Results
      inputs:
        testRunner: XUnit
        testResultsFiles: '$(Build.SourcesDirectory)/artifacts/TestResults/$(_configuration)/*.xml'
        mergeTestResults: true
        testRunTitle: '$(_os) $(_configuration)'
      condition: always()
    - task: PublishBuildArtifacts@1
      displayName: Publish Logs
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)/artifacts/log/$(_configuration)'
        ArtifactName: '$(_os) $(_configuration)'
      continueOnError: true
      condition: not(succeeded())