variables:
  - name: Build.Repository.Clean
    value: true
  - name: _HelixType
    value: build/product
  - name: _HelixSource
    value: pr/NuGet/NuGet.BuildTasks/$(Build.SourceBranch)
  - name: _HelixTestType
    value: test/product/
  - name: _XUnitProject
    value: $(Build.SourcesDirectory)/src/Microsoft.NuGet.Build.Tasks.Tests/Microsoft.NuGet.Build.Tasks.Tests.csproj
  - name: _XUnitTargetFramework
    value: netcoreapp2.0
  - name: _XUnitRunnerVersion
    value: 2.4.1
  - name: _DotNetCliPackageType
    value: sdk
  - name: _DotNetCliVersion
    value: 2.1.403
  - name: _HelixAccessToken
    value: ''

# CI and PR triggers
trigger:
- arcade

pr:
- arcade

jobs:
- template: /eng/common/templates/job/job.yml
  parameters:
    name: Windows_NT
    enableTelemetry: true
    enablePublishBuildArtifacts: true
    helixRepo: dotnet/arcade-minimalci-sample
    pool:
      name: NetCorePublic-Pool
      queue: BuildPool.Windows.10.Amd64.VS2017.Open
    strategy:
      matrix:
        debug_configuration:
          _BuildConfig: Debug
        release_configuration:
          _BuildConfig: Release
    steps:
    - script: eng\common\cibuild.cmd
        -configuration $(_BuildConfig)
        -prepareMachine
      name: Build
      displayName: Build
      condition: succeeded()
    - task: PublishBuildArtifacts@1
      displayName: Publish Logs to VSTS
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)/artifacts/log/$(_BuildConfig)'
        PublishLocation: Container
        ArtifactName: $(Agent.Os)_$(Agent.JobName)
      continueOnError: true
      condition: always()